#!/bin/sh

echo "1. Create"
echo "2. Migrate"
echo "3. Rollback"
echo ""
echo "Enter your action and press [ENTER] :"
read -r action

if [ "$action" = 1 ]
then
  echo "Set table name and press [ENTER] :"
  read tablename

  php vendor/bin/phinx create "$tablename" -c configs/phinx.php
fi

if [ "$action" = 2 ]
then
  php vendor/bin/phinx migrate -c configs/phinx.php
fi

if [ "$action" = 3 ]
then
    php vendor/bin/phinx rollback -c configs/phinx.php
fi